## Numpy array operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)
print("Basic slicing:", arr[2:7])
print("Slicing with step:", arr[1:8:2])
print("Slicing with negative step:", arr[7:2:-3])

[0 1 2 3 4 5 6 7 8 9]
Basic slicing: [2 3 4 5 6]
Slicing with step: [1 3 5 7]
Slicing with negative step: [7 4]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array:\n", arr_2d)
print("Specific element:", arr_2d[1, 2])
print("Entire row:", arr_2d[1, :])
print("Entire column:", arr_2d[:, 1])

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element: 6
Entire row: [4 5 6]
Entire column: [2 5 8]


## Sorting

In [4]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Unsorted array:", unsorted)
print("Sorted array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("2D unsorted array:\n", arr_2d_unsorted)
print("Sorted 2D array along axis 0:\n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array along axis 1:\n", np.sort(arr_2d_unsorted, axis=1))

Unsorted array: [3 1 4 1 5 9 2 6]
Sorted array: [1 1 2 3 4 5 6 9]
2D unsorted array:
 [[3 1 4]
 [1 5 9]
 [2 6 5]]
Sorted 2D array along axis 0:
 [[1 1 4]
 [2 5 5]
 [3 6 9]]
Sorted 2D array along axis 1:
 [[1 3 4]
 [1 5 9]
 [2 5 6]]


# Filter

In [5]:
numbers = np.arange(10)
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [0 2 4 6 8]


## Filter with mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [6 7 8 9]


## Fancy indexing vs np where()

In [7]:
indices = [0, 2, 4, 6]
print("Elements at specific indices:", numbers[indices])

np_where = np.where(numbers > 5)
print("Elements greater than 5:", numbers[np_where])

Elements at specific indices: [0 2 4 6]
Elements greater than 5: [6 7 8 9]


In [8]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print("Condition array:", condition_array)

Condition array: [ 0  1  2  3  4  5 24 28 32 36]


## Adding and removing data

In [ ]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

added = arr_1 + arr_2
print("Element-wise addition:", added)

combined = np.concatenate((arr_1, arr_2))
print("Combined array:", combined)

Combined array: [1 2 3 4 5 6]


## Array compatibility

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 7])

print("Compatibility Shapes:", a.shape == b.shape)
print("Compatibility Shapes:", a.shape == c.shape)

Compatibility Shapes: True
Compatibility Shapes: False


In [15]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Array after adding new row:\n", with_new_row)

new_column = np.array([[7], [8]])
with_new_column = np.hstack((original, new_column))
print("Array after adding new column:\n", with_new_column)

Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
Array after adding new column:
 [[1 2 7]
 [3 4 8]]


In [16]:
arr = np.array([1, 2 ,3 ,4 ,5])
print("Original array:", arr)
deleted = np.delete(arr, 2)
print("Array after deleting element at index 2:", deleted)

Original array: [1 2 3 4 5]
Array after deleting element at index 2: [1 2 4 5]
