## Numpy array and basics

In [5]:
import numpy as np

## Creating array from list

In [6]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [7]:
py_list = [1, 2, 3]
print("Python Multiplication List:", py_list * 2)

np_array = np.array([1, 2, 3])
print("NumPy Multiplication Array:", np_array * 2)

Python Multiplication List: [1, 2, 3, 1, 2, 3]
NumPy Multiplication Array: [2 4 6]


## Creating array from scratch

In [8]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))
print("Ones Array:\n", ones)

full = np.full((2, 2), 7)
print("Full Array:\n", full)

random = np.random.random((2, 3))
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.75188687 0.45269199 0.4553048 ]
 [0.85225063 0.96838376 0.95652532]]
Sequence Array: [0 2 4 6 8]


## Vector, Matrix and Tensor

In [9]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)

Original Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


## Array reshaping

In [11]:
arr = np.arange(12)
print("Original Array:", arr)

reshaped_arr = arr.reshape((3, 4))
print("Reshaped Array (3x4):\n", reshaped_arr)

resized_arr = arr.reshape((2, 2, 3))
print("Resized Array (2x2x3):\n", resized_arr)

flattened_arr = reshaped_arr.flatten()
print("Flattened Array:", flattened_arr)

raveled_arr = reshaped_arr.ravel()
print("Raveled Array:", raveled_arr)

transposed_arr = reshaped_arr.T
print("Transposed Array:\n", transposed_arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Resized Array (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
