In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))

In [12]:
np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)

In [13]:
loaded_array1 = np.load('array1.npy')
loaded_array2 = np.load('array2.npy')
loaded_array3 = np.load('array3.npy')
print("Loaded Array 1:\n", loaded_array1)
print("Loaded Array 2:\n", loaded_array2)
print("Loaded Array 3:\n", loaded_array3)

Loaded Array 1:
 [[1 2 3]
 [4 5 6]]
Loaded Array 2:
 [[0.28709386 0.99406829 0.3272813 ]
 [0.67641075 0.99957202 0.58756793]
 [0.43673017 0.27906569 0.69567182]]
Loaded Array 3:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
